[package]
name = "zerobuf"
version = "0.0.1"
authors = ["Badel2 <2badel2@gmail.com>"]
license = "MIT OR Apache-2.0"
description = """
A growable chunk of zeroed memory.
"""
repository = "https://github.com/badel2/zerobuf"
documentation = "https://docs.rs/zerobuf"

[dependencies]
